# Generated by Django 3.2.13 on 2022-05-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_watchlist_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ManyToManyField(to='watchlist_app.StreamPlatform'),
        ),
    ]
