# Generated by Django 3.2.13 on 2022-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_auto_20220515_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='platform',
            field=models.ManyToManyField(related_name='watchlist', to='watchlist_app.StreamPlatform'),
        ),
    ]
