# Generated by Django 3.2.13 on 2022-05-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0009_auto_20220515_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
