# Generated by Django 3.2.12 on 2022-05-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0017_alter_watchlist_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='watchlist_app.StreamPlatform'),
        ),
    ]
