# Generated by Django 3.2.12 on 2022-08-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0021_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='n_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
